name = 'My Portfolio'

[[accounts]]
names = ['Amex Gold']
users = [
    { name = 'Muhammad A Raksi', masks = ['51001'] },
    { name = 'Nadya A Raksi', masks = ['51019', '51012'] },
]

[[accounts]]
names = ['Robinhood Individual']
users = [
    { name = 'Muhammad A Raksi', masks = ['3674'] },
]

[[accounts]]
names = ['Wealthfront Individual']
users = [
    { name = 'Muhammad A Raksi', masks = ['6373'] },
]

[[accounts]]
names = ['Alight HSA']
users = [
    { name = 'Muhammad A Raksi', masks = ['1293'] },
]

[[accounts]]
names = ['Alight 401k']
users = [
    { name = 'Muhammad A Raksi' },
]